<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Using County Demographic Information to Predict the Number of Active Non-Federal Physicians in 1990</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 64px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h2 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h3 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h4 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h5 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h6 {
  padding-top: 69px;
  margin-top: -69px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="projects.html">Project</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Using County Demographic Information to Predict the Number of Active Non-Federal Physicians in 1990</h1>

</div>


<pre class="r"><code>library(faraway)
CDI&lt;-readRDS(&quot;~/Desktop/school/07_spring19/PSTAT\ 126/Final\ Project/CDI.rds&quot;)
Physicians &lt;- CDI$Physicians
TotalPop &lt;- log(CDI$TotalPop)
LandArea &lt;- CDI$LandArea
IncPerCap &lt;- CDI$IncPerCap
library(car)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:faraway&#39;:
## 
##     logit, vif</code></pre>
<pre class="r"><code>model1 &lt;- lm(Physicians~TotalPop+LandArea+IncPerCap)</code></pre>
<pre class="r"><code>avPlots(model1)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-2-1.png" width="672" /> In the added variable plots, it is clear that the predictor Total Population has a linear relationship with our response variable Physicians, whereas Land Area and Income per Capita have slopes close to <span class="math inline">\(0\)</span>, which implies there is no linear relationship with our response variable Physicians.</p>
<pre class="r"><code>pairs(Physicians~TotalPop+LandArea+IncPerCap)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-3-1.png" width="672" /> According to the plots generated by the pairs() function, it appears that there is a weak linear relationship between Total Population and the number of professionally active nonfederal physicians in 1990.</p>
<pre class="r"><code>summary(model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Physicians ~ TotalPop + LandArea + IncPerCap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1739.9  -495.4    -5.4   375.4  9938.9 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.706e+04  7.060e+02 -24.165   &lt;2e-16 ***
## TotalPop     1.427e+03  6.293e+01  22.683   &lt;2e-16 ***
## LandArea    -5.488e-02  2.865e-02  -1.916   0.0561 .  
## IncPerCap    1.285e-02  1.190e-02   1.079   0.2811    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 859.7 on 421 degrees of freedom
## Multiple R-squared:  0.6202, Adjusted R-squared:  0.6175 
## F-statistic: 229.2 on 3 and 421 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Fitting the model gives us the coeffiencients of Total Population, Land Area, and Income per Capita respectively as <span class="math inline">\(\hat{\beta_1} = 1.427\cdot10^3, \, \hat{\beta_2} = -5.488\cdot10^{-2}\)</span> and <span class="math inline">\(\hat{\beta_3} = 1.285\cdot10^{-2}\)</span>. For one unit increase in the natural log of Total Population, the expected change in our response Physicians is <span class="math inline">\(1.427\cdot10^3\)</span>, with all other predictors constant. For one unit increase in the Land Area, the expected change in our response Physicians is <span class="math inline">\(-5.488\cdot10^{-2}\)</span>, with all other predictors constant. For one unit increase in the Income per Cap, the expected change in our response Physicians is <span class="math inline">\(1.285\cdot10^{-2}\)</span>, with all other predictors constant.</p>
<pre class="r"><code>model1.res &lt;- model1$residuals
plot(model1, which = 1)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>plot(model1, which = 2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>shapiro.test(model1.res)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  model1.res
## W = 0.74213, p-value &lt; 2.2e-16</code></pre>
<p>Based off of these diagnostic plots, we see that there is a clear outlier in the Residual vs Fitted Plot and the Normal Q-Q Plot. In order, to see if we should remove this outlier from the data, we will do the following Hat Values and Cooks Distance tests.</p>
<pre class="r"><code>CDI.mod &lt;- CDI[-c(1),]
Physicians1 &lt;- CDI.mod$Physicians
TotalPop1 &lt;- log(CDI.mod$TotalPop)
LandArea1 &lt;- CDI.mod$LandArea
IncPerCap1 &lt;- CDI.mod$IncPerCap
model.mod &lt;- lm(Physicians1~TotalPop1+LandArea1+IncPerCap1)
plot(model.mod,which=1)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>plot(model.mod,which=2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-6-2.png" width="672" /> From the Residuals vs. Fitted and the Normal Q-Q Plot, we see that the data is non-normal, non-constant variance, and non-linear. Thus we will run a Box Cox Transformation to find the best transformation for Y.</p>
<pre class="r"><code>bc.mod &lt;- boxCox(model.mod)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>lambda.opt &lt;- bc.mod$x[which.max(bc.mod$y)]
lambda.opt</code></pre>
<pre><code>## [1] 0.02020202</code></pre>
<p>Box Cox Transforms gives us an optimal <span class="math inline">\(\lambda = 0.02020202\)</span>, rounding to the nearest whole number we get: <span class="math inline">\(\lambda = 0\)</span>. This implies that we will log transform our response variable, Physicians.</p>
<pre class="r"><code>model.mod1 &lt;- lm(log(Physicians1)~TotalPop1+LandArea1+IncPerCap1)
plot(model.mod1,which =1)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>plot(model.mod1,which=2) </code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code>#test normality
shapiro.test(summary(model.mod1)$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  summary(model.mod1)$residuals
## W = 0.98516, p-value = 0.000248</code></pre>
<p>By the Shapiro-Wilkes test, our new model violates the assumption of normality. Now we use powerTransform() to try to transform predictors.</p>
<pre class="r"><code>pc&lt;- powerTransform(cbind(TotalPop1,LandArea1,IncPerCap1)~1, CDI.mod)
summary(pc)</code></pre>
<pre><code>## bcPower Transformations to Multinormality 
##            Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
## TotalPop1    -6.1945       -6.19      -7.9111      -4.4779
## LandArea1    -0.0087        0.00      -0.0735       0.0561
## IncPerCap1   -0.3201       -0.50      -0.6026      -0.0375
## 
## Likelihood ratio test that transformation parameters are equal to 0
##  (all log transformations)
##                                LRT df       pval
## LR test, lambda = (0 0 0) 57.84979  3 1.6923e-12
## 
## Likelihood ratio test that no transformations are needed
##                                LRT df       pval
## LR test, lambda = (1 1 1) 977.7526  3 &lt; 2.22e-16</code></pre>
<pre class="r"><code>#transform land Area and IncPerCap
LandArea2&lt;-log(LandArea1)
IncPerCap2&lt;-IncPerCap1^-0.5
model.trans&lt;-lm(log(Physicians1)~TotalPop1+IncPerCap2+LandArea2)
summary(model.mod1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ TotalPop1 + LandArea1 + IncPerCap1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.41586 -0.28888 -0.01797  0.28796  1.65979 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.020e+01  3.805e-01 -26.817  &lt; 2e-16 ***
## TotalPop1    1.261e+00  3.392e-02  37.168  &lt; 2e-16 ***
## LandArea1   -3.024e-05  1.514e-05  -1.997   0.0465 *  
## IncPerCap1   3.501e-05  6.298e-06   5.558 4.86e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4541 on 420 degrees of freedom
## Multiple R-squared:  0.8303, Adjusted R-squared:  0.829 
## F-statistic: 684.8 on 3 and 420 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>summary(model.trans)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.42360 -0.28798 -0.01661  0.26716  1.56729 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -7.67280    0.55646 -13.789  &lt; 2e-16 ***
## TotalPop1      1.26095    0.03298  38.234  &lt; 2e-16 ***
## IncPerCap2  -164.42596   33.52788  -4.904 1.34e-06 ***
## LandArea2     -0.10561    0.02699  -3.913 0.000106 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4475 on 420 degrees of freedom
## Multiple R-squared:  0.8352, Adjusted R-squared:  0.834 
## F-statistic: 709.5 on 3 and 420 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>plot(model.trans,which=1)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>plot(model.trans,which=2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre class="r"><code>shapiro.test(summary(model.trans)$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  summary(model.trans)$residuals
## W = 0.99071, p-value = 0.008994</code></pre>
<pre class="r"><code>ncvTest(model.trans)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 2.304355, Df = 1, p = 0.12901</code></pre>
<p>Compare summaries of model.mod1 with model2. model2 has higher adjusted-R^2 and smaller residual standard error so it is a better model, but it still violated normality according to Shapiro-Wilkes test. It passes ncvTest which means variance is constant.</p>
<pre class="r"><code>#test interaction and quadratic terms
test.model&lt;-lm(log(Physicians1)~LandArea2+IncPerCap2+TotalPop1+I(LandArea2^2)+I(IncPerCap2^2)+I(TotalPop1^2)+LandArea2:IncPerCap2+LandArea2:TotalPop1+IncPerCap2:TotalPop1)

# compare summary tables
summary(model.trans)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.42360 -0.28798 -0.01661  0.26716  1.56729 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -7.67280    0.55646 -13.789  &lt; 2e-16 ***
## TotalPop1      1.26095    0.03298  38.234  &lt; 2e-16 ***
## IncPerCap2  -164.42596   33.52788  -4.904 1.34e-06 ***
## LandArea2     -0.10561    0.02699  -3.913 0.000106 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4475 on 420 degrees of freedom
## Multiple R-squared:  0.8352, Adjusted R-squared:  0.834 
## F-statistic: 709.5 on 3 and 420 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>summary(test.model)       #test model has bigger adj-r^2 and lower residual standard error</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + 
##     I(LandArea2^2) + I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:IncPerCap2 + 
##     LandArea2:TotalPop1 + IncPerCap2:TotalPop1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.39751 -0.28110 -0.01611  0.26325  1.61504 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)          -1.927e+01  9.196e+00  -2.096  0.03671 * 
## LandArea2             5.109e-01  5.682e-01   0.899  0.36911   
## IncPerCap2           -2.264e+02  7.699e+02  -0.294  0.76880   
## TotalPop1             2.815e+00  1.128e+00   2.495  0.01299 * 
## I(LandArea2^2)        4.455e-02  1.697e-02   2.624  0.00900 **
## I(IncPerCap2^2)      -5.821e+03  2.539e+04  -0.229  0.81875   
## I(TotalPop1^2)       -4.316e-02  3.819e-02  -1.130  0.25905   
## LandArea2:IncPerCap2 -8.964e+00  4.293e+01  -0.209  0.83470   
## LandArea2:TotalPop1  -8.883e-02  3.289e-02  -2.701  0.00721 **
## IncPerCap2:TotalPop1  1.575e+01  4.706e+01   0.335  0.73810   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4407 on 414 degrees of freedom
## Multiple R-squared:  0.8424, Adjusted R-squared:  0.839 
## F-statistic: 245.9 on 9 and 414 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#test 
anova(model.trans,test.model)    #decision --&gt; we need interactions</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2
## Model 2: log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:IncPerCap2 + 
##     LandArea2:TotalPop1 + IncPerCap2:TotalPop1
##   Res.Df    RSS Df Sum of Sq     F   Pr(&gt;F)   
## 1    420 84.091                               
## 2    414 80.404  6     3.687 3.164 0.004796 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#model selection
mod0&lt;-lm(log(Physicians1)~1)
mod.selection&lt;- step(mod0, scope=list(lower=mod0,upper=test.model), direction=&#39;forward&#39;)</code></pre>
<pre><code>## Start:  AIC=80.49
## log(Physicians1) ~ 1
## 
##                   Df Sum of Sq    RSS     AIC
## + TotalPop1        1    414.62  95.61 -627.51
## + I(TotalPop1^2)   1    412.77  97.46 -619.39
## + IncPerCap2       1    133.33 376.90  -45.93
## + I(IncPerCap2^2)  1    127.79 382.44  -39.74
## + LandArea2        1      9.79 500.44   74.28
## + I(LandArea2^2)   1      6.39 503.84   77.15
## &lt;none&gt;                         510.23   80.49
## 
## Step:  AIC=-627.51
## log(Physicians1) ~ TotalPop1
## 
##                   Df Sum of Sq    RSS     AIC
## + IncPerCap2       1    8.4566 87.158 -664.77
## + I(IncPerCap2^2)  1    8.3564 87.258 -664.29
## + LandArea2        1    6.7073 88.907 -656.35
## + I(LandArea2^2)   1    5.9300 89.684 -652.66
## + I(TotalPop1^2)   1    1.0934 94.521 -630.39
## &lt;none&gt;                         95.614 -627.51
## 
## Step:  AIC=-664.77
## log(Physicians1) ~ TotalPop1 + IncPerCap2
## 
##                        Df Sum of Sq    RSS     AIC
## + LandArea2             1   3.06618 84.091 -677.96
## + I(LandArea2^2)        1   2.43009 84.727 -674.76
## + I(TotalPop1^2)        1   0.59869 86.559 -665.70
## &lt;none&gt;                              87.158 -664.77
## + IncPerCap2:TotalPop1  1   0.03692 87.121 -662.95
## + I(IncPerCap2^2)       1   0.00014 87.157 -662.78
## 
## Step:  AIC=-677.96
## log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2
## 
##                        Df Sum of Sq    RSS     AIC
## + LandArea2:TotalPop1   1   1.65029 82.441 -684.36
## + I(LandArea2^2)        1   1.58644 82.505 -684.04
## + LandArea2:IncPerCap2  1   0.72184 83.370 -679.61
## + I(TotalPop1^2)        1   0.40385 83.688 -678.00
## &lt;none&gt;                              84.091 -677.96
## + IncPerCap2:TotalPop1  1   0.03988 84.052 -676.16
## + I(IncPerCap2^2)       1   0.00004 84.091 -675.96
## 
## Step:  AIC=-684.36
## log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2 + TotalPop1:LandArea2
## 
##                        Df Sum of Sq    RSS     AIC
## + I(LandArea2^2)        1   1.58180 80.859 -690.58
## &lt;none&gt;                              82.441 -684.36
## + I(TotalPop1^2)        1   0.25907 82.182 -683.70
## + IncPerCap2:TotalPop1  1   0.24804 82.193 -683.64
## + LandArea2:IncPerCap2  1   0.18936 82.252 -683.34
## + I(IncPerCap2^2)       1   0.03638 82.405 -682.55
## 
## Step:  AIC=-690.58
## log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2 + I(LandArea2^2) + 
##     TotalPop1:LandArea2
## 
##                        Df Sum of Sq    RSS     AIC
## &lt;none&gt;                              80.859 -690.58
## + I(TotalPop1^2)        1   0.36263 80.497 -690.48
## + IncPerCap2:TotalPop1  1   0.18892 80.670 -689.57
## + I(IncPerCap2^2)       1   0.07535 80.784 -688.97
## + LandArea2:IncPerCap2  1   0.02689 80.832 -688.72</code></pre>
<pre class="r"><code>summary(mod.selection)    # forward selection says to choose 5 predictor model with land area^2 and interaction between total pop and land area</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ TotalPop1 + IncPerCap2 + LandArea2 + 
##     I(LandArea2^2) + TotalPop1:LandArea2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.38860 -0.27596 -0.02478  0.26030  1.59008 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -12.76605    2.60918  -4.893 1.42e-06 ***
## TotalPop1              1.80663    0.19625   9.206  &lt; 2e-16 ***
## IncPerCap2          -179.14943   33.20060  -5.396 1.14e-07 ***
## LandArea2              0.44158    0.41900   1.054  0.29254    
## I(LandArea2^2)         0.04134    0.01446   2.860  0.00445 ** 
## TotalPop1:LandArea2   -0.08558    0.02934  -2.917  0.00373 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4398 on 418 degrees of freedom
## Multiple R-squared:  0.8415, Adjusted R-squared:  0.8396 
## F-statistic: 443.9 on 5 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>mod.selection11&lt;- step(test.model, scope=list(lower=mod0,upper=test.model), direction=&#39;backward&#39;)</code></pre>
<pre><code>## Start:  AIC=-684.97
## log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:IncPerCap2 + 
##     LandArea2:TotalPop1 + IncPerCap2:TotalPop1
## 
##                        Df Sum of Sq    RSS     AIC
## - LandArea2:IncPerCap2  1   0.00847 80.413 -686.93
## - I(IncPerCap2^2)       1   0.01021 80.415 -686.92
## - IncPerCap2:TotalPop1  1   0.02174 80.426 -686.86
## - I(TotalPop1^2)        1   0.24808 80.652 -685.66
## &lt;none&gt;                              80.404 -684.97
## - I(LandArea2^2)        1   1.33764 81.742 -679.97
## - LandArea2:TotalPop1   1   1.41635 81.821 -679.57
## 
## Step:  AIC=-686.93
## log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:TotalPop1 + 
##     IncPerCap2:TotalPop1
## 
##                        Df Sum of Sq    RSS     AIC
## - IncPerCap2:TotalPop1  1   0.02090 80.434 -688.81
## - I(IncPerCap2^2)       1   0.03220 80.445 -688.76
## - I(TotalPop1^2)        1   0.24131 80.654 -687.65
## &lt;none&gt;                              80.413 -686.93
## - LandArea2:TotalPop1   1   1.53221 81.945 -680.92
## - I(LandArea2^2)        1   1.65453 82.067 -680.29
## 
## Step:  AIC=-688.81
## log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:TotalPop1
## 
##                       Df Sum of Sq    RSS     AIC
## - IncPerCap2           1   0.00007 80.434 -690.81
## - I(IncPerCap2^2)      1   0.06290 80.497 -690.48
## - I(TotalPop1^2)       1   0.35018 80.784 -688.97
## &lt;none&gt;                             80.434 -688.81
## - LandArea2:TotalPop1  1   1.53546 81.969 -682.80
## - I(LandArea2^2)       1   1.71991 82.154 -681.84
## 
## Step:  AIC=-690.81
## log(Physicians1) ~ LandArea2 + TotalPop1 + I(LandArea2^2) + I(IncPerCap2^2) + 
##     I(TotalPop1^2) + LandArea2:TotalPop1
## 
##                       Df Sum of Sq    RSS     AIC
## - I(TotalPop1^2)       1    0.3502 80.784 -690.97
## &lt;none&gt;                             80.434 -690.81
## - LandArea2:TotalPop1  1    1.5690 82.003 -684.62
## - I(LandArea2^2)       1    1.7254 82.159 -683.82
## - I(IncPerCap2^2)      1    5.5042 85.938 -664.75
## 
## Step:  AIC=-690.97
## log(Physicians1) ~ LandArea2 + TotalPop1 + I(LandArea2^2) + I(IncPerCap2^2) + 
##     LandArea2:TotalPop1
## 
##                       Df Sum of Sq    RSS     AIC
## &lt;none&gt;                             80.784 -690.97
## - I(LandArea2^2)       1    1.6238 82.408 -684.53
## - LandArea2:TotalPop1  1    1.7419 82.526 -683.93
## - I(IncPerCap2^2)      1    5.7076 86.492 -664.03</code></pre>
<pre class="r"><code>summary(mod.selection11)  # backward elimination says to choose 5 pred model with land area, total pop, land area^2, incpercap^2 and landarea:totalpop</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ LandArea2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + LandArea2:TotalPop1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.39260 -0.27178 -0.02089  0.26148  1.58538 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -1.365e+01  2.591e+00  -5.268 2.21e-07 ***
## LandArea2            4.661e-01  4.188e-01   1.113  0.26646    
## TotalPop1            1.825e+00  1.961e-01   9.310  &lt; 2e-16 ***
## I(LandArea2^2)       4.192e-02  1.446e-02   2.899  0.00395 ** 
## I(IncPerCap2^2)     -1.184e+04  2.179e+03  -5.434 9.36e-08 ***
## LandArea2:TotalPop1 -8.811e-02  2.935e-02  -3.002  0.00284 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4396 on 418 degrees of freedom
## Multiple R-squared:  0.8417, Adjusted R-squared:  0.8398 
## F-statistic: 444.4 on 5 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#forward model
new.model&lt;-lm(log(Physicians1)~TotalPop1+IncPerCap2+LandArea2+I(LandArea2^2)+TotalPop1:LandArea2)
Anova(new.model,test.model)  #reject null --&gt; simplified model is better</code></pre>
<pre><code>## Anova Table (Type II tests)
## 
## Response: log(Physicians1)
##                      Sum Sq  Df   F value    Pr(&gt;F)    
## TotalPop1           273.243   1 1406.9222 &lt; 2.2e-16 ***
## IncPerCap2            5.632   1   29.0010 1.215e-07 ***
## LandArea2             2.223   1   11.4437 0.0007857 ***
## I(LandArea2^2)        1.582   1    8.1446 0.0045358 ** 
## TotalPop1:LandArea2   1.646   1    8.4734 0.0037985 ** 
## Residuals            80.404 414                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>ncvTest(new.model)     #constant variance</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 1.610426, Df = 1, p = 0.20443</code></pre>
<pre class="r"><code>shapiro.test(summary(new.model)$residuals) </code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  summary(new.model)$residuals
## W = 0.98988, p-value = 0.005104</code></pre>
<pre class="r"><code>influenceIndexPlot(new.model, id=TRUE)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>#backward model
new.model1&lt;-lm(log(Physicians1)~LandArea2+TotalPop1+I(LandArea2^2)+I(IncPerCap2^2)+LandArea2:TotalPop1)
anova(new.model1,test.model)    #reject null--&gt; simplified model is better</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(Physicians1) ~ LandArea2 + TotalPop1 + I(LandArea2^2) + I(IncPerCap2^2) + 
##     LandArea2:TotalPop1
## Model 2: log(Physicians1) ~ LandArea2 + IncPerCap2 + TotalPop1 + I(LandArea2^2) + 
##     I(IncPerCap2^2) + I(TotalPop1^2) + LandArea2:IncPerCap2 + 
##     LandArea2:TotalPop1 + IncPerCap2:TotalPop1
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    418 80.784                           
## 2    414 80.404  4   0.37967 0.4887  0.744</code></pre>
<pre class="r"><code>ncvTest(new.model1)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 1.380493, Df = 1, p = 0.24002</code></pre>
<pre class="r"><code>shapiro.test(summary(new.model1)$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  summary(new.model1)$residuals
## W = 0.99013, p-value = 0.00606</code></pre>
<pre class="r"><code>par(mfrow=c(1,2))
plot(model.trans,which=1)
plot(model.trans,which=2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,2))
plot(new.model,which=1)
plot(new.model,which=2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-10-3.png" width="672" /></p>
<pre class="r"><code>pc2&lt;- powerTransform(cbind(TotalPop1,LandArea2,IncPerCap2)~1, CDI.mod)
summary(pc2)</code></pre>
<pre><code>## bcPower Transformations to Multinormality 
##            Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
## TotalPop1    -6.1887       -6.19      -8.0292      -4.3481
## LandArea2     1.0813        1.00       0.6722       1.4904
## IncPerCap2    0.6423        1.00       0.0774       1.2072
## 
## Likelihood ratio test that transformation parameters are equal to 0
##  (all log transformations)
##                                LRT df       pval
## LR test, lambda = (0 0 0) 86.55739  3 &lt; 2.22e-16
## 
## Likelihood ratio test that no transformations are needed
##                                LRT df       pval
## LR test, lambda = (1 1 1) 75.10069  3 3.3307e-16</code></pre>
<p>Using the anova funtion to compare our two models, we reject the null hypothesis and conclude our model with the interactive terms is better. But it still violated normality.</p>
<p>Fitting the model gives us the coeffiencients of Total Population, Land Area, and Income per Capita respectively as <span class="math inline">\(\hat{\beta_1} = -1.367*10^{3}, \, \hat{\beta_2} = -8.318*10^{-2}\)</span> and <span class="math inline">\(\hat{\beta_3} = -1.708*10^{2}\)</span>. For one unit increase in the transformed Total Population, the expected change in our response Physicians is <span class="math inline">\(-1.367*10^{3}\)</span>, with all other predictors constant. For one unit increase in the transformed Land Area, the expected change in our response Physicians is <span class="math inline">\(-8.318*10^{-2}\)</span>, with all other predictors constant. For one unit increase in the transformed Income per Cap, the expected change in our response Physicians is <span class="math inline">\(-1.708*10^{2}\)</span>, with all other predictors constant.</p>
<p>We will conduct a global F-test to test the existence of a linear relationship.</p>
<pre class="r"><code>confint(model.mod1,level=0.95)</code></pre>
<pre><code>##                     2.5 %        97.5 %
## (Intercept) -1.095186e+01 -9.456019e+00
## TotalPop1    1.194075e+00  1.327424e+00
## LandArea1   -6.000077e-05 -4.743953e-07
## IncPerCap1   2.262518e-05  4.738589e-05</code></pre>
<p><strong>Hypothesis:</strong> <span class="math inline">\(H_0: \beta_1 = 0\)</span> vs <span class="math inline">\(H_1: \beta_1 \neq 0\)</span></p>
<p><strong>Test Statistic:</strong> This is given by the summary table of our full model</p>
<pre class="r"><code>summary(model.mod1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians1) ~ TotalPop1 + LandArea1 + IncPerCap1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.41586 -0.28888 -0.01797  0.28796  1.65979 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.020e+01  3.805e-01 -26.817  &lt; 2e-16 ***
## TotalPop1    1.261e+00  3.392e-02  37.168  &lt; 2e-16 ***
## LandArea1   -3.024e-05  1.514e-05  -1.997   0.0465 *  
## IncPerCap1   3.501e-05  6.298e-06   5.558 4.86e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4541 on 420 degrees of freedom
## Multiple R-squared:  0.8303, Adjusted R-squared:  0.829 
## F-statistic: 684.8 on 3 and 420 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From the summary table, we see that the F-statistic has a value of <span class="math inline">\(639\)</span> with corresponding p-value of <span class="math inline">\(p-value &lt; 2.2*10^{-16}\)</span>.</p>
<p><strong>Decision Rule:</strong> Reject <span class="math inline">\(H_0\)</span> when F is large, or when the p-value is less than the significance level <span class="math inline">\(\alpha = 0.01\)</span>. In this case <span class="math inline">\(p-value = 2.2*10^{-16} &lt; 0.05 = \alpha\)</span>. Thus we reject the null hypothesis. We conclude that is at least one significant linear relationship between the predictors and the response at significance level of <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<pre class="r"><code>#use ncvTest on the full model to test whether or not the variance is constant
ncvTest(model.mod1)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 1.223083, Df = 1, p = 0.26876</code></pre>
<p>According to the output of the Non-constant Variance Score Test, at a significance of <span class="math inline">\(\alpha=0.05\)</span>, we can reject the null hypothesis that the variance of the residuals is constant. This aligns with the plot of the standardized residuals vs. fitted values.</p>
<pre class="r"><code>#refit the model using WLS due to non-constant variance
model.mod.wlm&lt;-lm(log(Physicians)~.,data=CDI.mod,weights=1/model.mod1$fitted.values)
plot(model.mod.wlm,which=3)</code></pre>
<pre><code>## Warning: not plotting observations with leverage one:
##   1, 2, 5, 8, 9, 10, 13, 14, 15, 16, 17, 18, 20, 21, 25, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 40, 42, 44, 45, 46, 48, 49, 52, 55, 56, 57, 60, 61, 63, 64, 65, 67, 68, 69, 71, 72, 74, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 92, 93, 94, 95, 96, 98, 99, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 137, 138, 139, 141, 143, 144, 145, 148, 150, 151, 153, 155, 158, 159, 160, 161, 162, 163, 165, 167, 168, 169, 170, 171, 172, 174, 176, 177, 178, 179, 180, 181, 182, 183, 184, 186, 188, 189, 191, 194, 195, 196, 197, 198, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 215, 216, 217, 218, 219, 222, 223, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 260, 261, 262, 263, 264, 265, 267, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 280, 282, 284, 285, 286, 287, 288, 289, 290, 291, 293, 294, 295, 296, 297, 298, 303, 304, 305, 306, 307, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 322, 323, 325, 326, 327, 328, 330, 332, 333, 334, 335, 336, 337, 338, 339, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 355, 356, 357, 358, 360, 361, 362, 363, 364, 365, 366, 367, 368, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 383, 384, 386, 387, 389, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 405, 406, 407, 409, 410, 412, 413, 414, 415, 416, 419, 420, 421, 423, 424</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Now, we are going to investigate the model:</p>
<p><span class="math inline">\(E(Physicians)=\hat\beta_0+(TotalPop)xi_1+(Region)xi_2\)</span></p>
<pre class="r"><code>Region &lt;- CDI$Region
x1 &lt;- ifelse(as.character(Region) == &#39;1&#39;, 1,0)
x2 &lt;- ifelse(as.character(Region) == &#39;2&#39;, 1,0)
x3 &lt;- ifelse(as.character(Region) == &#39;3&#39;, 1,0)
x4 &lt;- ifelse(as.character(Region) == &#39;4&#39;, 1,0)
personal_inc&lt;-CDI$PersonalInc

categ.lm&lt;-lm(log(Physicians)~log(TotalPop)+personal_inc+x1+x2+x3)
summary(categ.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians) ~ log(TotalPop) + personal_inc + 
##     x1 + x2 + x3)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.42131 -0.31860 -0.02713  0.26241  1.67826 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -3.595e+01  1.686e+00 -21.322   &lt;2e-16 ***
## log(TotalPop)  1.666e+01  6.767e-01  24.613   &lt;2e-16 ***
## personal_inc   2.524e-06  4.166e-06   0.606   0.5450    
## x1             1.233e-01  7.223e-02   1.707   0.0886 .  
## x2             1.640e-02  7.245e-02   0.226   0.8211    
## x3             1.037e-01  6.759e-02   1.535   0.1256    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4725 on 419 degrees of freedom
## Multiple R-squared:  0.821,  Adjusted R-squared:  0.8189 
## F-statistic: 384.3 on 5 and 419 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Region 1:</strong> <span class="math inline">\(\hat{Y}=(-1.088\cdot10^{1})+1.360log(TotalPop)-2.712PersonalInc+1.3\cdot10^{-1}\)</span></p>
<p><strong>Region 2:</strong> <span class="math inline">\(\hat{Y}=(-1.088\cdot10^{1})+1.360log(TotalPop)-2.712PersonalInc+1.913\cdot10^{-2}\)</span></p>
<p><strong>Region 3:</strong> <span class="math inline">\(\hat{Y}=(-1.088\cdot10^{1})+1.360log(TotalPop)-2.712PersonalInc+1.039\cdot10^{-1}\)</span></p>
<p><strong>Region 4:</strong> <span class="math inline">\(\hat{Y}=(-1.088\cdot10^{1})+1.360log(TotalPop)-2.712PersonalInc\)</span></p>
<p>This model is called a parallel regression model because they have the same slopes, making each line parallel to each other.</p>
<pre class="r"><code>model.full&lt;-lm(log(Physicians)~log(TotalPop)+Region)
model.red&lt;-lm(log(Physicians)~log(TotalPop))
anova(model.red,model.full)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(Physicians) ~ log(TotalPop)
## Model 2: log(Physicians) ~ log(TotalPop) + Region
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    423 94.734                           
## 2    422 94.472  1    0.2622 1.1712 0.2798</code></pre>
<p>After controlling the effects of Region, we have found that the reduced model is more favorable than the full model. Since our p-value is <span class="math inline">\(0.2608\)</span>, we do not have enough evidence to reject the null hypothesis <span class="math inline">\(H_0\)</span>.</p>
<pre class="r"><code>pop65&lt;-CDI$Pop65
crimes&lt;-CDI$Crimes
bachelor&lt;-CDI$Bachelor
poverty&lt;-CDI$Poverty

mod.0&lt;-lm(log(Physicians)~1)
mod.1&lt;-lm(log(Physicians)~log(TotalPop)+pop65+crimes+bachelor+poverty+personal_inc)

step(mod.0,scope=list(lower=mod.0,upper=mod.1),direction=&#39;forward&#39;)</code></pre>
<pre><code>## Start:  AIC=89.88
## log(Physicians) ~ 1
## 
##                 Df Sum of Sq    RSS     AIC
## + log(TotalPop)  1    427.89  94.73 -633.93
## + personal_inc   1    289.44 233.19 -251.11
## + crimes         1    173.81 348.81  -79.96
## + bachelor       1    116.44 406.18  -15.25
## &lt;none&gt;                       522.62   89.88
## + pop65          1      0.30 522.32   91.63
## + poverty        1      0.01 522.61   91.87
## 
## Step:  AIC=-633.93
## log(Physicians) ~ log(TotalPop)
## 
##                Df Sum of Sq    RSS     AIC
## + bachelor      1   15.4065 79.328 -707.36
## + pop65         1    1.1719 93.562 -637.22
## + poverty       1    0.7974 93.937 -635.52
## &lt;none&gt;                      94.734 -633.93
## + personal_inc  1    0.0645 94.670 -632.22
## + crimes        1    0.0091 94.725 -631.97
## 
## Step:  AIC=-707.36
## log(Physicians) ~ log(TotalPop) + bachelor
## 
##                Df Sum of Sq    RSS     AIC
## + poverty       1    7.7258 71.602 -748.91
## + pop65         1    7.0691 72.259 -745.03
## &lt;none&gt;                      79.328 -707.36
## + crimes        1    0.2844 79.043 -706.89
## + personal_inc  1    0.0003 79.327 -705.36
## 
## Step:  AIC=-748.91
## log(Physicians) ~ log(TotalPop) + bachelor + poverty
## 
##                Df Sum of Sq    RSS     AIC
## + pop65         1   10.1703 61.432 -812.02
## &lt;none&gt;                      71.602 -748.91
## + personal_inc  1    0.0523 71.550 -747.22
## + crimes        1    0.0012 71.601 -746.92
## 
## Step:  AIC=-812.02
## log(Physicians) ~ log(TotalPop) + bachelor + poverty + pop65
## 
##                Df Sum of Sq    RSS     AIC
## &lt;none&gt;                      61.432 -812.02
## + personal_inc  1  0.036793 61.395 -810.27
## + crimes        1  0.013080 61.419 -810.11</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians) ~ log(TotalPop) + bachelor + poverty + 
##     pop65)
## 
## Coefficients:
##   (Intercept)  log(TotalPop)       bachelor        poverty          pop65  
##     -33.92497       15.17194        0.04569        0.03821        0.04185</code></pre>
<p>After applying the forward selection algorithm, using AIC as a criterion function, we have found that the best model is the one that has 4 predictors: <strong>log(TotalPop), bachelor, poverty, and pop65.</strong></p>
<pre class="r"><code>step(mod.1,scope=list(lower=mod.0,upper=mod.1),direction=&#39;backward&#39;)</code></pre>
<pre><code>## Start:  AIC=-808.27
## log(Physicians) ~ log(TotalPop) + pop65 + crimes + bachelor + 
##     poverty + personal_inc
## 
##                 Df Sum of Sq     RSS     AIC
## - crimes         1     0.000  61.395 -810.27
## - personal_inc   1     0.024  61.419 -810.11
## &lt;none&gt;                        61.395 -808.27
## - poverty        1     9.933  71.328 -746.54
## - pop65          1    10.112  71.507 -745.48
## - bachelor       1    30.850  92.245 -637.25
## - log(TotalPop)  1   105.350 166.745 -385.64
## 
## Step:  AIC=-810.27
## log(Physicians) ~ log(TotalPop) + pop65 + bachelor + poverty + 
##     personal_inc
## 
##                 Df Sum of Sq     RSS     AIC
## - personal_inc   1     0.037  61.432 -812.02
## &lt;none&gt;                        61.395 -810.27
## - pop65          1    10.155  71.550 -747.22
## - poverty        1    10.856  72.251 -743.08
## - bachelor       1    31.248  92.643 -637.42
## - log(TotalPop)  1   105.707 167.102 -386.73
## 
## Step:  AIC=-812.02
## log(Physicians) ~ log(TotalPop) + pop65 + bachelor + poverty
## 
##                 Df Sum of Sq    RSS     AIC
## &lt;none&gt;                        61.43 -812.02
## - pop65          1    10.170  71.60 -748.91
## - poverty        1    10.827  72.26 -745.03
## - bachelor       1    31.336  92.77 -638.85
## - log(TotalPop)  1   291.851 353.28  -70.55</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians) ~ log(TotalPop) + pop65 + bachelor + 
##     poverty)
## 
## Coefficients:
##   (Intercept)  log(TotalPop)          pop65       bachelor        poverty  
##     -33.92497       15.17194        0.04185        0.04569        0.03821</code></pre>
<p>After applying the backwards selection algorithm, using AIC as a criterion function, we have found that the best model is the one that has 4 predictors: <strong>log(TotalPop), bachelor, poverty, and pop65.</strong></p>
<pre class="r"><code>library(leaps)
model.reg&lt;-regsubsets(cbind(log(TotalPop),Region,pop65,crimes,bachelor,poverty),log(Physicians),data=CDI)
summary.reg&lt;-summary(model.reg)
summary.reg$adjr2</code></pre>
<pre><code>## [1] 0.8183053 0.8474934 0.8620192 0.8813360 0.8834030 0.8831461</code></pre>
<pre class="r"><code>summary.reg$cp</code></pre>
<pre><code>## [1] 236.717387 131.753984  80.115728  11.505846   5.078553   7.000000</code></pre>
<pre class="r"><code>summary.reg$bic</code></pre>
<pre><code>## [1] -713.7060 -783.0859 -820.5816 -879.6381 -882.0677 -876.0954</code></pre>
<pre class="r"><code>summary.reg</code></pre>
<pre><code>## Subset selection object
## 6 Variables  (and intercept)
##          Forced in Forced out
##              FALSE      FALSE
## Region       FALSE      FALSE
## pop65        FALSE      FALSE
## crimes       FALSE      FALSE
## bachelor     FALSE      FALSE
## poverty      FALSE      FALSE
## 1 subsets of each size up to 6
## Selection Algorithm: exhaustive
##              Region pop65 crimes bachelor poverty
## 1  ( 1 ) &quot;*&quot; &quot; &quot;    &quot; &quot;   &quot; &quot;    &quot; &quot;      &quot; &quot;    
## 2  ( 1 ) &quot;*&quot; &quot; &quot;    &quot; &quot;   &quot; &quot;    &quot;*&quot;      &quot; &quot;    
## 3  ( 1 ) &quot;*&quot; &quot; &quot;    &quot; &quot;   &quot; &quot;    &quot;*&quot;      &quot;*&quot;    
## 4  ( 1 ) &quot;*&quot; &quot; &quot;    &quot;*&quot;   &quot; &quot;    &quot;*&quot;      &quot;*&quot;    
## 5  ( 1 ) &quot;*&quot; &quot;*&quot;    &quot;*&quot;   &quot; &quot;    &quot;*&quot;      &quot;*&quot;    
## 6  ( 1 ) &quot;*&quot; &quot;*&quot;    &quot;*&quot;   &quot;*&quot;    &quot;*&quot;      &quot;*&quot;</code></pre>
<p>According the the adjusted adjusted <span class="math inline">\(R^{2}\)</span>,<span class="math inline">\(Mallows C_p\)</span>, and BIC values from the regsubsets output, the model with 5 predictors is the best one. However, since both the forwards and backwards elimination algorithms found that the model with 4 predictors is the best one, we are going to run a partial F-test on that model.</p>
<pre class="r"><code>physicians.old&lt;-lm(log(Physicians)~log(TotalPop))
physicians.new&lt;-lm(log(Physicians)~log(TotalPop)+bachelor+poverty+pop65+personal_inc)
anova(physicians.old,physicians.new)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(Physicians) ~ log(TotalPop)
## Model 2: log(Physicians) ~ log(TotalPop) + bachelor + poverty + pop65 + 
##     personal_inc
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    423 94.734                                  
## 2    419 61.395  4    33.339 56.882 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Hypothesis:</strong> <span class="math inline">\(H_0:\beta_1=0\)</span>, <span class="math inline">\(H_1:\beta_1\neq1\)</span></p>
<p><strong>Result:</strong> With a p-value of <span class="math inline">\(2.2\cdot10^{-16}\)</span>, we have significant evidence to reject the null hypothesis.</p>
<p><strong>Conclusion:</strong> At <span class="math inline">\(\alpha=0.05\)</span>, the improvement from adding the predictors: Pop65, Crimes, Bachelor, Poverty and PersonalInc is statistically significant. According to the partial F-test, the new model is better than the old model.</p>
<pre class="r"><code>physicians.hats&lt;-hatvalues(physicians.new)
physicans.cooks&lt;-cooks.distance(physicians.new)
influenceIndexPlot(physicians.new,id=TRUE)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>According to the diagnostic plots of the leaverage and Cook’s Distance values, the data on rows <span class="math inline">\(114\)</span>, <span class="math inline">\(119\)</span>, and <span class="math inline">\(179\)</span> are influential points.</p>
<pre class="r"><code>plot(physicians.new,which=3)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>summary(physicians.new)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Physicians) ~ log(TotalPop) + bachelor + poverty + 
##     pop65 + personal_inc)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.40985 -0.23094  0.02089  0.21941  1.30266 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -3.338e+01  1.365e+00 -24.450  &lt; 2e-16 ***
## log(TotalPop)  1.495e+01  5.566e-01  26.859  &lt; 2e-16 ***
## bachelor       4.564e-02  3.125e-03  14.603  &lt; 2e-16 ***
## poverty        3.840e-02  4.461e-03   8.607  &lt; 2e-16 ***
## pop65          4.182e-02  5.024e-03   8.325 1.21e-15 ***
## personal_inc   1.697e-06  3.386e-06   0.501    0.617    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3828 on 419 degrees of freedom
## Multiple R-squared:  0.8825, Adjusted R-squared:  0.8811 
## F-statistic: 629.5 on 5 and 419 DF,  p-value: &lt; 2.2e-16</code></pre>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
